config/routes.rb
Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin == true } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources 'doom_meter', only: [:show, :new, :create, :destroy] do
    resources 'doom', only: :create
  end
  post '/get_dooms', to: "doom_meter#get_dooms"
  post '/send_invite', to: "doom_meter#send_invite"
  get '/apply_invite/:uid', to: "doom_meter#apply_invite", as: 'apply_invite'
  post '/like', to: "doom#like"

  root to: 'doom_meter#show'
  get "*path" => redirect("/")
end

app/models/doom.rb
class Doom < ApplicationRecord
  belongs_to :user
  belongs_to :d_meter
  has_many :likes

  validates :level, :text, presence: true
  validates_length_of :text, minimum: 1, maximum: 100, allow_blank: true

  after_create :change_last_active_doom

  private
  def change_last_active_doom
    dooms = d_meter.dooms.order(:created_at).where(user_id: user_id, created_at: (created_at.beginning_of_day..created_at.end_of_day))
    dooms[-2].update(active: false) if dooms.size > 1
  end
end

app/controllers/doom_controller.rb
class DoomController < ApplicationController

  def create
    doom_meter = DMeter.find(params["doom_meter_id"])
    current_user.dooms.create!(doom_params.merge(d_meter_id: doom_meter.id, level: doom_meter.levels[params["doom"]['level']]))
    redirect_to doom_meter_path(doom_meter.friendly_id)
  end

  def like
    like = current_user.likes.where(doom_id: params['doom_id']).first
    response =
        if like.present?
          like.destroy
          { heart: 'fa-thumbs-o-up', unheart: 'fa-thumbs-up', count: like.doom.likes.count > 0 ? like.doom.likes.count : '' }
        else
          like = current_user.likes.create(doom_id: params['doom_id'])
          { heart: 'fa-thumbs-up', unheart: 'fa-thumbs-o-up', count: like.doom.likes.count }
        end
    render json: response
  end

  private
  def doom_params
    params.require(:doom).permit(:text)
  end
end

app/helpers/doom_helper.rb
module DoomHelper
end

app/views/doom/_all_dooms.html.erb
<div class="count_previous_dooms">
  <span><%= 'doom friends' %></span>
  <span class="right grey_color"><%= @doom_meter.count_active_dooms %></span>
</div>

<div class="friends_dooms">
  <% @dooms.each do |k,dooms| %>
    <div class="previous_doom">
      <div class="clearfix"><div class="left width-40"><%= k %></div></div>
      <% dooms.each do |doom| %>
        <div class="previous_doom_info">
          <div class="border-bottom clearfix">
            <div class="left width-40 user-doom"><%= doom.user.username %></div>
            <div class="doom_like_count">
              <span><%= doom.likes.count if doom.likes.count > 0 %></span>
              <i class="fa <%= current_user.likes.where(doom_id: doom.id).first.present? ? 'fa fa-thumbs-up' : 'fa fa-thumbs-o-up' %>" aria-hidden="true" onclick="Like($(this), <%= doom.id %>)"></i>
            </div>
          </div>
          <div class="grey_color">Today i’m feeling</div>
          <div class="red_uppercase_text"><%= @doom_meter[doom.level] %></div>
          <div class="grey_color">Because</div>
          <div><%= doom.text %></div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/doom/_dooms.html.erb
<div id="user_dooms">
  <div class="doom_button_group clearfix">
    <%= button_tag 'my doom', class: 'doom_btn active_btn left_btn', onclick: "getDoom($(this), 'my_doom', '#{@doom_meter.friendly_id}')" %>
    <%= button_tag 'general', class: 'doom_btn right_btn', onclick: "getDoom($(this), 'general', '#{@doom_meter.friendly_id}')" %>
  </div>
  <div class="doom_info_block"><%= render partial: 'doom/my_dooms' %></div>
</div>

app/views/doom/_form.html.erb
<div class="new_doom_form">
  <div><%= "today i'm feeling" %></div>
  <%= form_for @doom, url: doom_meter_doom_index_path(@doom_meter), method: :post do |f| %>
    <div><%= text_field_tag 'doom[level]', @doom_meter.doom_lvl_0, onclick:"showListLevels()", required: true %><div class="caret"></div></div>
    <ul id="list_levels">
      <% @doom_meter.levels.each do |k,v| %>
        <li onclick="hideListLevels($(this))"><a href="#"><%= k %></a></li>
      <% end %>
    </ul>
    <div class="because">
      <div class="doomy"><%= 'doomy' %></div>
      <div><%= 'because' %></div>
      <div><%= f.text_area :text, rows: "3", placeholder: 'Your Reason', maxlength: 100, required: true %></div>
      <%= f.submit 'submit', class: 'doom_btn submit_btn' %>
    </div>
  <% end %>
</div>

app/views/doom/_my_dooms.html.erb
<%= render partial: 'doom/form' %>
<div class="text-center">
  <% if @doom_meter.user != current_user %>
    <%= link_to new_doom_meter_path do %>
      <div class="custom_doom_meter"><%= button_tag 'create a custom doom meter', class: 'button_doom_meter' %></div>
    <% end %>
  <% else %>
    <%= link_to new_doom_meter_path do %>
      <div class="custom_doom_meter_two_button"><%= button_tag 'create a custom doom meter', class: 'button_doom_meter two_button' %></div>
    <% end %>
    <%= link_to doom_meter_path(@doom_meter), method: :delete, data: {confirm: "Are you sure?"} do %>
      <div class="custom_doom_meter_two_button"><%= button_tag 'delete current doom meter', class: 'button_doom_meter two_button' %></div>
    <% end %>
  <% end %>
</div>

<div class="dooms">
  <div class="count_previous_dooms">
    <span><%= 'my previous dooms' %></span>
    <span class="right grey_color"><%= @previous_dooms.size %></span>
  </div>
  <div class="previous_dooms">
    <% @previous_dooms.each do |doom| %>
      <div class="previous_doom">
        <div class="clearfix">
          <div class="left width-40"><%= doom.created_at.strftime('%B %d, %Y') %></div>
          <div class="doom_like_count">
            <span><%= doom.likes.size if doom.likes.size > 0 %></span>
            <i class="fa <%= current_user.liked?(doom.id) %>" aria-hidden="true"></i>
          </div>
        </div>
        <div class="previous_doom_info">
          <div class="grey_color">Today i’m feeling</div>
          <div class="red_uppercase_text">
            <div><%= @doom_meter[doom.level] %></div>
          </div>
          <div class="grey_color">Because</div>
          <div><%= doom.text %></div>
        </div>
      </div>
    <% end %>
  </div>
</div>