config/routes.rb
Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin == true } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources 'doom_meter', only: [:show, :new, :create, :destroy] do
    resources 'doom', only: :create
  end
  post '/get_dooms', to: "doom_meter#get_dooms"
  post '/send_invite', to: "doom_meter#send_invite"
  get '/apply_invite/:uid', to: "doom_meter#apply_invite", as: 'apply_invite'
  post '/like', to: "doom#like"

  root to: 'doom_meter#show'
  get "*path" => redirect("/")
end

app/views/shared/_login_form.html.erb
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div id="login_block">
        <div class="modal-body">
          <div class="login_link">log in</div>
          <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class="field">
              <%= f.text_field :username, placeholder: 'Username', required: true %>
            </div>
            <div class="field">
              <%= f.password_field :password, placeholder: 'Your Password', required: true %>
            </div>
            <%= link_to "forgot password?", new_password_path(resource_name), class: 'login-field left-margin' %>
            <%= link_to "Create an account", '#', "data-dismiss" => "modal", onclick:"$('.nav_registration_link').click();", class: 'login-field right-margin' %><br />
            <%= recaptcha_tags %>
            <div class="actions"><%= f.submit "submit" %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_registration_form.html.erb
<div class="modal fade" id="registrationModal" tabindex="-1" role="dialog" aria-labelledby="registrationModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div id="registration_block">
        <div class="modal-body">
          <div class="login_link">create your doom account</div>
          <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
            <%#= render "devise/shared/error_messages", resource: resource %>
            <div class="field">
              <%= f.email_field :email, placeholder: 'Your Email', required: true %>
            </div>
            <div class="field">
              <%= f.text_field :username, placeholder: 'Username', required: true %>
            </div>
            <div class="field">
              <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %> characters minimum)</em>
                <br />
              <% end %>
              <%= f.password_field :password, placeholder: 'Your Password', required: true %>
            </div>
            <div class="field">
              <%= f.password_field :password_confirmation, placeholder: 'Your Password Confirmation', required: true %>
            </div>
            <%= recaptcha_tags %>
            <div class="checkbox inline">
              <%= f.label :tos_agreement do %>
                <%= f.check_box :tos_agreement %>
                <%= link_to 'Terms of Service', '#' %>
              <% end %>
            </div>
            <div class="actions"><%= f.submit "submit" %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>