config/routes.rb
Rails.application.routes.draw do

  authenticate :user, lambda { |u| u.admin == true } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources 'doom_meter', only: [:show, :new, :create, :destroy] do
    resources 'doom', only: :create
  end
  post '/get_dooms', to: "doom_meter#get_dooms"
  post '/send_invite', to: "doom_meter#send_invite"
  get '/apply_invite/:uid', to: "doom_meter#apply_invite", as: 'apply_invite'
  post '/like', to: "doom#like"

  root to: 'doom_meter#show'
  get "*path" => redirect("/")
end

app/controllers/doom_meter_controller.rb
class DoomMeterController < ApplicationController
  before_action :authenticate_user!, except: [:show, :send_invite]
  before_action :set_doom_meter

  def show
    dooms_info if current_user
    @doom_level = @my_doom&.level || @doom_meter.current_doom_level
  end

  def get_dooms
    if params["doom_type"] == 'general'
      @dooms = @doom_meter.active_dooms.order(created_at: :desc).group_by{ |t| t.created_at.strftime('%B %d, %Y') }
      html = render_to_string(partial: "doom/all_dooms")
    else
      @dooms = @doom_meter.active_dooms.order(created_at: :desc)
      if current_user
        dooms_info
        html = render_to_string(partial: "doom/my_dooms")
      end
    end
    @doom_level = @my_doom&.level || @doom_meter.current_doom_level
    html_doom_meter = render_to_string(partial: "doom_meter/doom_meter")
    render json: { html: html, doom_meter: html_doom_meter }, status: :ok
  end

  def new
    @new_doom_meter = current_user.d_meters.new()
    @doom_level = @doom_meter.current_doom_level
  end

  def create
    new_doom_meter = current_user.d_meters.new(doom_meter_params)
    if new_doom_meter.save
      redirect_to doom_meter_path(new_doom_meter.friendly_id)
    else
      redirect_to new_doom_meter_path(id: @doom_meter.friendly_id)
    end
  end

  def destroy
    @doom_meter.destroy
    flash['notice'] = "Doom Meter #{@doom_meter.name} deleted succeffuly!"
    redirect_to root_path
  end

  def send_invite
    invite = Invite.new(email: params[:email], d_meter_id: @doom_meter.id, uid: SecureRandom.uuid)
    if invite.save
      UserMailer.send_invite(invite.uid, invite.email).deliver_now
      render json: {message: 'Invitation was sent successfully.'}, status: :ok
    else
      errors = ''
      invite.errors.full_messages.each { |error| errors += "<p><strong>#{error}</strong></p>" }
      render json: {message: errors}, status: :unprocessable_entity
    end
  end

  def apply_invite
    invite = Invite.where(uid: params[:uid]).first
    invite.update(active: true)
    redirect_to doom_meter_path(invite.d_meter)
  end

  private
  def set_doom_meter
    return @doom_meter = DMeter.first if params["id"].blank?
    @doom_meter = DMeter.find(params["id"])
  rescue => error
    redirect_to root_path
  end

  def doom_meter_params
    params.require(:d_meter).permit(:name,
                                   :doom_lvl_0,
                                   :doom_lvl_1,
                                   :doom_lvl_2,
                                   :doom_lvl_3,
                                   :doom_lvl_4,
                                   :doom_lvl_5,
                                   :doom_lvl_6,
                                   :doom_lvl_7,
                                   :doom_lvl_8,
                                   :doom_lvl_9,
                                   :doom_lvl_10,
                                   :doom_lvl_11,
                                   :doom_lvl_12,
                                   :count_days,
                                   :public
    )
  end

  def dooms_info
    @doom = current_user.dooms.new()
    @previous_dooms = @doom_meter.active_dooms.where(user_id: current_user.id).order(created_at: :desc)
    @my_doom = @previous_dooms.first if @previous_dooms.first&.created_at&.to_date == Date.today
  end
end

app/helpers/doom_meter_helper.rb
module DoomMeterHelper
end

app/views/doom_meter/_doom_meter.html.erb
<div class="main_doom_meter">
  <% if @my_doom.present? %>
    <div class="invite">
      <%= email_field_tag 'invite_email' %>
      <button onclick="sendInvite(<%= @doom_meter.id %>)">send invite</button>
    </div>
  <% end %>
  <div class="radius"></div>
  <div class="radius-in"></div>

  <%- 13.times do |i| %>
    <div class="level lvl<%= i %>"></div>
    <% if "doom_lvl_#{i}" == ( @my_doom&.level || @doom_level) %>
      <%- margin = i < 6 ? 'margin-left-85' : i == 6 ? 'margin-left-58' : '' %>
      <% if @my_doom.present? %>
        <div class="current-text-level height-80 text<%= i %> <%= margin %> left<%= i %>">
          <div class="red-level"><%= @doom_meter["doom_lvl_#{i}"] %></div>
          <%= image_tag 'point.svg' %>
          <div class="text_doom" title="<%= @my_doom.text %>"><%= @my_doom.text %></div>
          <hr>
          <div>
            <%= "Share My Doomy:" %>
            <%= rails_social_share_button_tag('Share to Doom Meter', desc: 'test description') %>
          </div>
        </div>
      <% else %>
        <div class="current-text-level text<%= i %> <%= margin %> left<%= i %> top<%= i %>">
          <div class="red-level"><%= @doom_meter["doom_lvl_#{i}"] %></div>
          <%= image_tag 'point.svg' %>
          <span class="margin-left-5"><%= @doom_meter.count_active_dooms %></span>
          <%= ' total Doomies' %>
        </div>
      <% end %>
    <% else %>
      <div class="text-level text<%= i %>"><%= @doom_meter["doom_lvl_#{i}"] %></div>
    <% end %>
  <% end %>

  <div class="radius-level-in"></div>
  <div class="point-level point<%= DMeter.point_level(@doom_level) %>"></div>
  <div class="center-circle">
    <%#= image_tag 'scull.svg' %>
    <div class="user-name" style="margin-top:60px;"><%= current_user&.username || 'general doomy' %></div>
  </div>
  <div class="center-circle-back"></div>
  <%= image_tag 'arrow.svg', class: "arrow arr#{DMeter.point_level(@doom_level)}" %>
  <div class="doom_meter-title">
    <div class="doom_meter-name"><%= @doom_meter&.name %></div>
  </div>
  <div class="back-block"></div>
  <div class="banner"><%= image_tag 'doom.svg' %></div>
</div>

app/views/doom_meter/_form.html.erb
<div class="new_doom_meter_form">
  <div><%= 'New Doom Meter' %></div>
  <%= form_for @new_doom_meter, url: doom_meter_index_path, method: :post do |f| %>

    <div><%= f.text_field :name, placeholder: 'Name', class: 'dmeter_field', maxlength: 30, required: true %></div>

    <%- 13.times do |i| %>
      <div><%= f.text_field "doom_lvl_#{i}", class: 'dmeter_field', maxlength: 25, placeholder: "level #{i}", required: true %></div>
    <% end %>

    <div class="line-height-35">
      <%= label 'days for calculate', 'days to calculate average', style:"margin-top: 5px;font-size:9px;"%>
      <%= f.number_field "count_days", value: 1, min: 1, required: true, class: 'dmeter_field' %>
    </div>
    <div class="public">
      <%= f.label :public do %>
        <%= f.check_box :public %>
        <%= "Public" %>
      <% end %>
    </div>
    <div><%= f.submit 'submit', class: 'doom_btn submit_btn' %></div>
  <% end %>
</div>

app/views/doom_meter/new.html.erb
<div id="container_doom_meter">
  <div id="doom-meter"><%= render partial: 'doom_meter' %></div>
  <div id="user_dooms">
    <div class="doom_info_block"><%= render partial: 'doom_meter/form' %></div>
  </div>
</div>

app/views/doom_meter/show.html.erb
<div id="container_doom_meter">
  <div id="doom-meter"><%= render partial: 'doom_meter' %></div>
  <%= render partial: 'doom/dooms' if current_user %>
</div>